### ISSUE TITLE
Feature Request: Forward UDP ports alongside TCP ports using upnp

### ISSUE THREAD

**Issue by Git-North** [nanonestor/universalator#14]
Since this project describes itself as "A modded Minecraft Server installation & launching script file" many mods utilize UDP ports the most noticible and popular ones being:
- Racknetify
- Geyser
- Simple Voicechat
- Plasmo
- MWeb
any many more...

**Comment by nanonestor** [comment]
Added support to toggle between using the UPnP for - TCP, or TCP&UDP, or UDP

**Comment by nanonestor** [comment]
In an interesting development - I ripped out MiniUPNP yesterday and have integrated in a completely different open source UPNP port forwarding program - :)  I present version 2.38  

[https://github.com/nanonestor/universalator/blob/latest/Universalator-2.38.bat](https://github.com/nanonestor/universalator/blob/latest/Universalator-2.38.bat)

New UPNP forwarding utility program
[https://github.com/itssimple/Portforwarded.Server/tree/2.0.1](https://github.com/itssimple/Portforwarded.Server/tree/2.0.1)

The Univ can now use UPNP to port forward TCP and UDP at the same time, each with a different port number.  Port and other networking related settings are now stored in settings-universalator.txt for remembering between runs.  Also it auto detects if the simple voice chat mod config is present and syncs it's config value to the UDP set value.  I might go the extra mile and add sync with some other mods, but SVC is pretty popular and done.

It seems like it works really well!  Hopefully instead of 51% of the time every 80% of the time, it's just a straight up 51% of the time - LOL.  It has some releases for Linux x64 and MacOS, so eventually i'll add it to those versions also.
