### ISSUE TITLE
Universalator downloads the 32 bit Java instead of the 64 Bit

### ISSUE THREAD

**Issue by GoldenFurredFox** [nanonestor/universalator#2]
**Operating System version (i.e. Windows version, etc):** Windows 10 Home 64 Bit

**Universalator version:** 2.4

**Describe the bug**
Universalator downloads the 32 bit version of Java and doesn't take into account your computer's actual architecture.

**Screenshots**
![image](https://github.com/nanonestor/universalator/assets/28793227/5808c3da-2765-43b4-a290-19db166b1412)
Example of Spark profiler showing maximum RAM allocated being 2 gigs

![image](https://github.com/nanonestor/universalator/assets/28793227/5d974369-5e45-4f00-a1b7-93301e2bb200)
Example of settings-universalator.txt being set to 8 gigs.

**Comment by nanonestor** [comment]
Greetings! 

The Universalator does download and utilize 64 bit java - as seen in the code setting which things to download on lines 1211-1245.
[https://github.com/nanonestor/universalator/blob/latest/Universalator-2.4.bat]
(https://github.com/nanonestor/universalator/blob/latest/Universalator-2.4.bat)

Spark is likely showing the amount of memory/ram currently allocated - but not the MAX that is set as maximum (Xmx) because java hasn't allocated up to that maximum yet.

**Comment by nanonestor** [comment]
Also FYI - if you have a java installed to your OS that you'd rather use - you can enter in the main menu the word 'OVERRIDE' and until the program is closed it will use your OS installed java for launches
