### ISSUE TITLE
Online mode

### ISSUE THREAD

**Issue by TheBigSTN** [nanonestor/universalator#4]
**Operating System version (i.e. Windows version, etc):**

**Universalator version:**
latest

**Describe the bug**
every time i launch universalator it resets some of the server configs like online mode 
if i whant online mode to be false i need to open universalator and then schange the setting but the problem is that i need to do it every time i launck universalator

**Screenshots**

**Comment by nanonestor** [comment]
Hello, what you are describing is purposely built into the script.  Multiplayer Minecraft requires online mode to be true when users join.  

Turning online mode off is usually done for the purpose of allowing cracked clients to connect, which is software piracy.  This is not something I will support aiding, same with all of the mainstream Minecraft modding community.  Minecraft accounts are cheap and last forever, anyone without should purchase a legal account, and run your server in online mode.

**Comment by dinkley** [comment]
That may be what it's "usually done for", but there are cases where a server running on a home's local network does not have access to the internet. Forcing online mode makes it so nobody on the local network can connect to their own local server if it doesn't have access to Mojang's authentication servers. This can happen for a number of reasons: 
- The user is experiencing network connectivity issues
- The user does not have internet access (at all)
- Mojang are experiencing network connectivity issues

You shouldn't deny legal players access to their own servers just because their or Mojang's network is down. The `online-mode` property exists for that reason. You have no reason to assume that the player is attempting to pirate Minecraft.

Additionally, Universalator overriding what the end user has specifically defined in configuration files should not happen. You could maybe make an argument for Universlator correcting a typo, or a setting that could prevent the server from starting, but denying them an option that was provided by Mojang themselves for the exact reason above, is not within the scope of this project. This restriction goes against user-friendliness and will only introduce problems.


I understand that you don't want illegitimate users to use your script, but it would be better if you removed this restriction as it is more likely to hinder legitimate players.
