### ISSUE TITLE
Using on Mac - Ram issue

### ISSUE THREAD

**Issue by theone1super** [nanonestor/universalator#9]
MacOSX Ventura 13.6.9
Universalator 2.3 (Linux version on Mac)

Bug Description:
Configuring the server starter, I'm stuck at the RAM section where no input is valid. I put in the minimum all the way to the full amount of ram on my device, but I am still given the same response of "You cannot enter a value that leaves less than 1gb of ram/memory left available! Press any key to try a new entry...", whether I input 0 all the way to 8GB.

I plan to use Universalator to check which mods are client vs server side, so the number in itself is somewhat irrelevant for me, but any way to get around this issue would be greatly appreciated!

Screenshots:
<img width="613" alt="Screenshot 2024-08-20 at 3 33 20 PM" src="https://github.com/user-attachments/assets/12e515c7-7b5c-4960-abda-be09ec052fd4">
<img width="602" alt="Screenshot 2024-08-20 at 3 33 33 PM" src="https://github.com/user-attachments/assets/b0310102-2c1e-4631-97be-715c8b6f8acf">

**Comment by nanonestor** [comment]
Greetings MacOS user

How much ram does it display as total / available at the top of this entry?  Or is that not displayed?

**Comment by theone1super** [comment]
It did not display the amount of ram available on any of the entries. 

Note: I downloaded the windows version and used it on Parralels desktop and had 0 issues, was able to get it to work

**Comment by nanonestor** [comment]
I changed the code of the Linux/macOS version to ignore trying to determine system ram values when using macOS - see if it gets you through now?  Thanks.

[https://github.com/nanonestor/universalator/archive/refs/heads/latest-linux.zip](https://github.com/nanonestor/universalator/archive/refs/heads/latest-linux.zip)

Yes the Windows version works great because everyone's Windows 10+ have the same system commands and tools.  Making the Linux/macOS version is much trickier because there are so many Linux distributions and all of them have their own special differences... ...
